on:
  push:
    branches: master

name: bookdown

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUBPAT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc

      - name: Cache Renv packages
        uses: actions/cache@v1
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-  

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
      
      - name: Install Keras and TensorFlow
        run: |
          R -e 'reticulate::install_miniconda()'
          R -e 'tensorflow::install_tensorflow(version = "2.1.0")'
          R -e 'keras::install_keras(tensorflow = "2.1.0")'

      - name: Build site
        run: |
          Rscript faq.R
          Rscript build.R
          ./deploy.sh
